# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: java-hello
      run: |
         cd java-hello
         mvn -B compile 
         mvn -B exec:java  -Dexec.mainClass="cn.devit.demo.Hello" -Dexec.args=""
         mvn -B exec:java  -Dexec.mainClass="cn.devit.demo.FizzBuzz" -Dexec.args="100"
    - name: kotlin-hello
      run: |
        cd kotlin-hello
        mvn compile
        mvn exec:java  -Dexec.mainClass="cn.devit.demo.HelloKt" -Dexec.args=""
        mvn exec:java  -Dexec.mainClass="cn.devit.demo.FizzBuzzKt" -Dexec.args="100"    
    - name: scala-hello
      run: |
        cd scala-hello
        mvn -B compile
        mvn exec:java -Dexec.mainClass="Hello" -Dexec.args=""
        mvn exec:java -Dexec.mainClass="FizzBuzz" -Dexec.args="100"  
    - name: clojure-hello
      run: |
        mvn -B compile
        mvn exec:java  -Dexec.mainClass=Hello 
        mvn exec:java  -Dexec.mainClass="FizzBuzz" -Dexec.args="100"
